// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV300ouIL7NC-auxyzP-Sr3WyKC6WiX4c',
    appId: '1:798557170930:web:25164a10bddcfd9885b46b',
    messagingSenderId: '798557170930',
    projectId: 'jazeera-733f3',
    authDomain: 'jazeera-733f3.firebaseapp.com',
    storageBucket: 'jazeera-733f3.firebasestorage.app',
    measurementId: 'G-FB6NR3GTKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2xPOrX09qphpuwuWNTN0SM4gLhJPoIOw',
    appId: '1:798557170930:android:fcec33e5726661cb85b46b',
    messagingSenderId: '798557170930',
    projectId: 'jazeera-733f3',
    storageBucket: 'jazeera-733f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9019bwFcY4yGUay2xwrB1hpw-fDKuCA0',
    appId: '1:798557170930:ios:5f117f65dfe7ef3485b46b',
    messagingSenderId: '798557170930',
    projectId: 'jazeera-733f3',
    storageBucket: 'jazeera-733f3.firebasestorage.app',
    iosBundleId: 'com.example.workConnectKerala',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9019bwFcY4yGUay2xwrB1hpw-fDKuCA0',
    appId: '1:798557170930:ios:5f117f65dfe7ef3485b46b',
    messagingSenderId: '798557170930',
    projectId: 'jazeera-733f3',
    storageBucket: 'jazeera-733f3.firebasestorage.app',
    iosBundleId: 'com.example.workConnectKerala',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV300ouIL7NC-auxyzP-Sr3WyKC6WiX4c',
    appId: '1:798557170930:web:0c16029760f1cb3e85b46b',
    messagingSenderId: '798557170930',
    projectId: 'jazeera-733f3',
    authDomain: 'jazeera-733f3.firebaseapp.com',
    storageBucket: 'jazeera-733f3.firebasestorage.app',
    measurementId: 'G-7ZFDQ0MV1L',
  );
}
